/**
 * Generates supabase/seed.sql from the typed content in src/content.
 *
 * Running this rather than hand-writing SQL means the seed and the local
 * fallback dataset can never drift apart. Node 24 strips the types natively:
 *
 *   node scripts/gen-seed.ts
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { services } from "../src/content/services.ts";
import { industries } from "../src/content/industries.ts";
import { projects } from "../src/content/projects.ts";
import { posts, topics } from "../src/content/posts.ts";
import { heroBoard, heroModel } from "../src/content/pcb.ts";
import {
  certifications, clients, faqs, footerNavigation, navigation, processStages,
  settings, stats, team, testimonials,
} from "../src/content/site.ts";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "null";
  return `'${String(v).replace(/'/g, "''")}'`;
};
const jsonb = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const arr = (v: string[]) => (v.length ? `array[${v.map(q).join(",")}]` : "'{}'");
const uuid = (ns: string, key: string) => {
  // Deterministic v4-shaped id so re-running the seed is idempotent.
  let h1 = 0x811c9dc5;
  for (const c of `${ns}:${key}`) { h1 ^= c.charCodeAt(0); h1 = Math.imul(h1, 0x01000193) >>> 0; }
  let h2 = 0x9e3779b9;
  for (const c of `${key}:${ns}`) { h2 ^= c.charCodeAt(0); h2 = Math.imul(h2, 0x85ebca6b) >>> 0; }
  const hex = (n: number) => (n >>> 0).toString(16).padStart(8, "0");
  const a = hex(h1), b = hex(h2), c = hex(h1 ^ h2), d = hex((h1 + h2) >>> 0);
  return `${a}-${b.slice(0, 4)}-4${b.slice(5, 8)}-a${c.slice(1, 4)}-${c.slice(4)}${d}`;
};

const L: string[] = [];
const say = (s = "") => L.push(s);

say("-- =============================================================");
say("-- Anode seed data");
say("-- GENERATED by scripts/gen-seed.ts — do not edit by hand.");
say("-- Idempotent: ids are derived from slugs, so re-running upserts.");
say("-- =============================================================");
say("");
say("begin;");
say("");

/* ------------------------------------------------------- settings */
say("-- ---------- site_settings ----------");
const settingRows: [string, string, unknown][] = [
  ["hero.eyebrow", "hero", settings.hero.eyebrow],
  ["hero.headline_lines", "hero", settings.hero.headlineLines],
  ["hero.accent_word", "hero", settings.hero.accentWord],
  ["hero.subcopy", "hero", settings.hero.subcopy],
  ["hero.cta_primary", "hero", settings.hero.ctaPrimary],
  ["hero.cta_secondary", "hero", settings.hero.ctaSecondary],
  ["hero.proof_caption", "hero", settings.hero.proofCaption],
  ["copy.process_heading", "copy", settings.copy.processHeading],
  ["copy.section_headings", "copy", settings.copy.sectionHeadings],
  ["copy.cta_band", "copy", settings.copy.ctaBand],
  ["copy.differentiators", "copy", settings.copy.differentiators],
  ["copy.comparison", "copy", settings.copy.comparison],
  ["contact.company_name", "contact", settings.contact.companyName],
  ["contact.legal_name", "contact", settings.contact.legalName],
  ["contact.email", "contact", settings.contact.email],
  ["contact.sales_email", "contact", settings.contact.salesEmail],
  ["contact.phone", "contact", settings.contact.phone],
  ["contact.address_lines", "contact", settings.contact.addressLines],
  ["contact.hours", "contact", settings.contact.hours],
  ["contact.response_promise", "contact", settings.contact.responsePromise],
  ["contact.geo", "contact", settings.contact.geo],
  ["social.links", "social", settings.social],
  ["seo.title_template", "seo", settings.seo.titleTemplate],
  ["seo.default_title", "seo", settings.seo.defaultTitle],
  ["seo.description", "seo", settings.seo.description],
  ["seo.timezone", "seo", settings.seo.timezone],
  ["features.flags", "features", settings.features],
];
for (const [key, group, value] of settingRows) {
  say(
    `insert into public.site_settings (key, value, group_name) values (${q(key)}, ${jsonb(value)}, ${q(group)})\n` +
      `  on conflict (key) do update set value = excluded.value, group_name = excluded.group_name;`,
  );
}
say("");

/* ----------------------------------------------------- navigation */
say("-- ---------- navigation_items ----------");
let navOrder = 0;
for (const item of navigation) {
  const id = uuid("nav", item.id);
  say(
    `insert into public.navigation_items (id, label, href, description, icon, location, column_group, order_index, is_external)\n` +
      `  values (${q(id)}, ${q(item.label)}, ${q(item.href)}, ${q(item.description)}, ${q(item.icon)}, 'header', null, ${++navOrder}, false)\n` +
      `  on conflict (id) do update set label = excluded.label, href = excluded.href, order_index = excluded.order_index;`,
  );
  let childOrder = 0;
  for (const child of item.children) {
    say(
      `insert into public.navigation_items (id, parent_id, label, href, description, icon, location, order_index, is_external)\n` +
        `  values (${q(uuid("nav", child.id))}, ${q(id)}, ${q(child.label)}, ${q(child.href)}, ${q(child.description)}, ${q(child.icon)}, 'header', ${++childOrder}, false)\n` +
        `  on conflict (id) do update set label = excluded.label, href = excluded.href, description = excluded.description;`,
    );
  }
}
for (const item of footerNavigation) {
  say(
    `insert into public.navigation_items (id, label, href, location, column_group, order_index, is_external)\n` +
      `  values (${q(uuid("nav", item.id))}, ${q(item.label)}, ${q(item.href)}, 'footer', ${q(item.columnGroup)}, ${item.orderIndex}, false)\n` +
      `  on conflict (id) do update set label = excluded.label, href = excluded.href, column_group = excluded.column_group;`,
  );
}
say("");

/* ------------------------------------------------------- services */
say("-- ---------- services ----------");
for (const s of services) {
  const id = uuid("service", s.slug);
  say(
    `insert into public.services (id, slug, title, tagline, summary, body_html, icon, deliverables, tooling, order_index, status, published_at, seo_title, seo_description)\n` +
      `  values (${q(id)}, ${q(s.slug)}, ${q(s.title)}, ${q(s.tagline)}, ${q(s.summary)}, ${q(s.bodyHtml)}, ${q(s.icon)}, ${arr(s.deliverables)}, ${jsonb(s.tooling)}, ${s.orderIndex}, 'published', now(), ${q(s.seoTitle)}, ${q(s.seoDescription)})\n` +
      `  on conflict (id) do update set title = excluded.title, tagline = excluded.tagline, summary = excluded.summary,\n` +
      `    body_html = excluded.body_html, icon = excluded.icon, deliverables = excluded.deliverables, tooling = excluded.tooling,\n` +
      `    order_index = excluded.order_index, seo_title = excluded.seo_title, seo_description = excluded.seo_description;`,
  );
  say(`delete from public.service_features where service_id = ${q(id)};`);
  s.features.forEach((f, i) => {
    say(
      `insert into public.service_features (id, service_id, title, description, icon, order_index)\n` +
        `  values (${q(uuid("feature", `${s.slug}:${f.id}`))}, ${q(id)}, ${q(f.title)}, ${q(f.description)}, ${q(f.icon)}, ${i + 1});`,
    );
  });
}
say("");

/* ----------------------------------------------------- industries */
say("-- ---------- industries ----------");
for (const ind of industries) {
  const id = uuid("industry", ind.slug);
  say(
    `insert into public.industries (id, slug, name, summary, body_html, icon, standards, order_index, status, published_at, seo_title, seo_description)\n` +
      `  values (${q(id)}, ${q(ind.slug)}, ${q(ind.name)}, ${q(ind.summary)}, ${q(ind.bodyHtml)}, ${q(ind.icon)}, ${arr(ind.standards)}, ${ind.orderIndex}, 'published', now(), ${q(ind.seoTitle)}, ${q(ind.seoDescription)})\n` +
      `  on conflict (id) do update set name = excluded.name, summary = excluded.summary, body_html = excluded.body_html,\n` +
      `    standards = excluded.standards, order_index = excluded.order_index;`,
  );
  ind.serviceSlugs.forEach((slug, i) => {
    say(
      `insert into public.industry_services (industry_id, service_id, order_index)\n` +
        `  values (${q(id)}, ${q(uuid("service", slug))}, ${i + 1}) on conflict do nothing;`,
    );
  });
}
say("");

/* --------------------------------------------------------- people */
say("-- ---------- team_members ----------");
for (const m of team) {
  say(
    `insert into public.team_members (id, name, role, bio, linkedin_url, order_index, status, published_at)\n` +
      `  values (${q(uuid("team", m.id))}, ${q(m.name)}, ${q(m.role)}, ${q(m.bio)}, ${q(m.linkedinUrl)}, ${m.orderIndex}, 'published', now())\n` +
      `  on conflict (id) do update set name = excluded.name, role = excluded.role, bio = excluded.bio;`,
  );
}
say("");

/* -------------------------------------------------------- clients */
say("-- ---------- clients ----------");
for (const c of clients) {
  say(
    `insert into public.clients (id, name, logo_mark, website_url, featured, order_index, status, published_at)\n` +
      `  values (${q(uuid("client", c.id))}, ${q(c.name)}, ${q(c.logoMark)}, ${q(c.websiteUrl)}, ${c.featured}, ${c.orderIndex}, 'published', now())\n` +
      `  on conflict (id) do update set name = excluded.name, featured = excluded.featured, order_index = excluded.order_index;`,
  );
}
say("");

/* ------------------------------------------------------- projects */
say("-- ---------- projects ----------");
for (const p of projects) {
  const id = uuid("project", p.slug);
  say(
    `insert into public.projects (id, slug, title, client_name, industry_id, summary, challenge, approach, outcome, body_html, year, duration_weeks, board_spec, is_confidential, featured, order_index, status, published_at, seo_title, seo_description)\n` +
      `  values (${q(id)}, ${q(p.slug)}, ${q(p.title)}, ${q(p.isConfidential ? null : p.clientName)}, ${p.industry ? q(uuid("industry", p.industry.slug)) : "null"}, ${q(p.summary)}, ${q(p.challenge)}, ${q(p.approach)}, ${q(p.outcome)}, ${q(p.bodyHtml)}, ${p.year}, ${p.durationWeeks ?? "null"}, ${jsonb(p.boardSpec)}, ${p.isConfidential}, ${p.featured}, ${p.orderIndex}, 'published', now(), ${q(p.seoTitle)}, ${q(p.seoDescription)})\n` +
      `  on conflict (id) do update set title = excluded.title, summary = excluded.summary, challenge = excluded.challenge,\n` +
      `    approach = excluded.approach, outcome = excluded.outcome, body_html = excluded.body_html,\n` +
      `    board_spec = excluded.board_spec, featured = excluded.featured, order_index = excluded.order_index;`,
  );
  p.services.forEach((s, i) => {
    say(
      `insert into public.project_services (project_id, service_id, order_index)\n` +
        `  values (${q(id)}, ${q(uuid("service", s.slug))}, ${i + 1}) on conflict do nothing;`,
    );
  });
  say(`delete from public.project_metrics where project_id = ${q(id)};`);
  p.metrics.forEach((m, i) => {
    say(
      `insert into public.project_metrics (id, project_id, label, value, unit, order_index)\n` +
        `  values (${q(uuid("metric", `${p.slug}:${i}`))}, ${q(id)}, ${q(m.label)}, ${q(m.value)}, ${q(m.unit)}, ${i + 1});`,
    );
  });
}
say("");

/* --------------------------------------------------- process/faqs */
say("-- ---------- process_stages ----------");
for (const s of processStages) {
  say(
    `insert into public.process_stages (id, step_number, title, short_description, detail, icon, order_index, status, published_at)\n` +
      `  values (${q(uuid("stage", s.id))}, ${s.stepNumber}, ${q(s.title)}, ${q(s.shortDescription)}, ${jsonb(s.detail)}, ${q(s.icon)}, ${s.stepNumber}, 'published', now())\n` +
      `  on conflict (id) do update set title = excluded.title, short_description = excluded.short_description, detail = excluded.detail;`,
  );
}
say("");

say("-- ---------- post_topics + posts ----------");
topics.forEach((t, i) => {
  say(
    `insert into public.post_topics (id, slug, name, order_index) values (${q(uuid("topic", t.slug))}, ${q(t.slug)}, ${q(t.name)}, ${i + 1})\n` +
      `  on conflict (id) do update set name = excluded.name;`,
  );
});
for (const p of posts) {
  say(
    `insert into public.posts (id, slug, title, excerpt, body_html, topic_id, author_id, status, published_at, seo_title, seo_description)\n` +
      `  values (${q(uuid("post", p.slug))}, ${q(p.slug)}, ${q(p.title)}, ${q(p.excerpt)}, ${q(p.bodyHtml)}, ${p.topic ? q(uuid("topic", p.topic.slug)) : "null"}, ${p.author ? q(uuid("team", p.author.id)) : "null"}, 'published', ${q(p.publishedAt)}::timestamptz, ${q(p.seoTitle)}, ${q(p.seoDescription)})\n` +
      `  on conflict (id) do update set title = excluded.title, excerpt = excluded.excerpt, body_html = excluded.body_html;`,
  );
}
say("");

say("-- ---------- testimonials ----------");
for (const t of testimonials) {
  say(
    `insert into public.testimonials (id, quote, author_name, author_role, company, project_id, industry_id, featured, status, published_at)\n` +
      `  values (${q(uuid("testimonial", t.id))}, ${q(t.quote)}, ${q(t.authorName)}, ${q(t.authorRole)}, ${q(t.company)}, ${t.projectSlug ? q(uuid("project", t.projectSlug)) : "null"}, ${t.industrySlug ? q(uuid("industry", t.industrySlug)) : "null"}, ${t.featured}, 'published', now())\n` +
      `  on conflict (id) do update set quote = excluded.quote, featured = excluded.featured;`,
  );
}
say("");

say("-- ---------- certifications, stats, faqs ----------");
for (const c of certifications) {
  say(
    `insert into public.certifications (id, name, issuer, description, valid_until, order_index, status, published_at)\n` +
      `  values (${q(uuid("cert", c.id))}, ${q(c.name)}, ${q(c.issuer)}, ${q(c.description)}, ${c.validUntil ? `${q(c.validUntil)}::date` : "null"}, ${certifications.indexOf(c) + 1}, 'published', now())\n` +
      `  on conflict (id) do update set name = excluded.name, description = excluded.description;`,
  );
}
for (const s of stats) {
  say(
    `insert into public.stats (id, label, value, prefix, suffix, context, order_index, status, published_at)\n` +
      `  values (${q(uuid("stat", s.id))}, ${q(s.label)}, ${s.value}, ${q(s.prefix)}, ${q(s.suffix)}, ${q(s.context)}, ${s.orderIndex}, 'published', now())\n` +
      `  on conflict (id) do update set label = excluded.label, value = excluded.value;`,
  );
}
for (const f of faqs) {
  say(
    `insert into public.faqs (id, question, answer, scope, order_index, status, published_at)\n` +
      `  values (${q(uuid("faq", f.id))}, ${q(f.question)}, ${q(f.answer)}, ${q(f.scope)}, ${f.orderIndex}, 'published', now())\n` +
      `  on conflict (id) do update set question = excluded.question, answer = excluded.answer, scope = excluded.scope;`,
  );
}
say("");

/* ------------------------------------------------------------ 3D */
say("-- ---------- pcb_models, hotspots, variants ----------");
const modelId = uuid("pcb", heroModel.slug);
say(
  `insert into public.pcb_models (id, name, slug, storage_path, board_definition, camera_default, camera_limits, scale, is_hero, status, published_at)\n` +
    `  values (${q(modelId)}, ${q(heroModel.name)}, ${q(heroModel.slug)}, ${q(heroModel.storagePath)}, ${jsonb(heroBoard)}, ${jsonb(heroModel.cameraDefault)}, ${jsonb(heroModel.cameraLimits)}, ${heroModel.scale}, true, 'published', now())\n` +
    `  on conflict (id) do update set board_definition = excluded.board_definition,\n` +
    `    camera_default = excluded.camera_default, camera_limits = excluded.camera_limits;`,
);
say(`delete from public.pcb_hotspots where model_id = ${q(modelId)};`);
heroModel.hotspots.forEach((h, i) => {
  say(
    `insert into public.pcb_hotspots (id, model_id, label, value, detail, icon, position, normal, anchor, body, link_url, variant_key, order_index)\n` +
      `  values (${q(uuid("hotspot", h.id))}, ${q(modelId)}, ${q(h.label)}, ${q(h.value)}, ${q(h.detail)}, ${q(h.icon)}, ${jsonb(h.position)}, ${jsonb(h.normal)}, ${q(h.anchor)}, ${q(h.body)}, ${q(h.linkUrl)}, ${q(h.variantKey)}, ${i + 1});`,
  );
});
say(`delete from public.pcb_model_variants where model_id = ${q(modelId)};`);
heroModel.variants.forEach((v, i) => {
  say(
    `insert into public.pcb_model_variants (id, model_id, key, display_name, icon, config, order_index)\n` +
      `  values (${q(uuid("variant", `${heroModel.slug}:${v.key}`))}, ${q(modelId)}, ${q(v.key)}, ${q(v.displayName)}, ${q(v.icon)}, ${jsonb(v.config)}, ${i + 1});`,
  );
});
say("");
say("commit;");
say("");

const out = join(dirname(fileURLToPath(import.meta.url)), "..", "supabase", "seed.sql");
writeFileSync(out, L.join("\n"), "utf8");
console.log(`Wrote ${out} — ${L.length} lines`);
